# Generated by Django 3.1 on 2020-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='context0',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='context1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='context2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='context3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='context4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='context5',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='context6',
            field=models.TextField(default='', null=True),
        ),
    ]
