# Generated by Django 3.1 on 2020-08-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200817_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='context0',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='context1',
            new_name='guarantee',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='idx',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='context2',
            new_name='interestRate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='context3',
            new_name='liog',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='context4',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='context5',
            new_name='seat',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='context6',
            new_name='termgrt',
        ),
    ]
